-- ESNYCA CoopLink - SQL Server schema (MSSMS)
-- Run this in your SQL Server database.

-- Users
CREATE TABLE dbo.Users (
  Id UNIQUEIDENTIFIER NOT NULL CONSTRAINT PK_Users PRIMARY KEY DEFAULT NEWID(),
  Email NVARCHAR(320) NOT NULL,
  PasswordHash NVARCHAR(255) NOT NULL,
  Role NVARCHAR(32) NOT NULL CONSTRAINT DF_Users_Role DEFAULT N'individual',
  DisplayName NVARCHAR(120) NOT NULL,
  PhoneNumber NVARCHAR(40) NULL,
  Region NVARCHAR(40) NULL,
  RegistrationNumber NVARCHAR(80) NULL,
  PhysicalAddress NVARCHAR(255) NULL,
  Content NVARCHAR(MAX) NULL,
  ProfilePicUrl NVARCHAR(2048) NULL,
  CompanyAddress NVARCHAR(255) NULL,
  LocationLat FLOAT NULL,
  LocationLng FLOAT NULL,
  CreatedAt DATETIME2 NOT NULL CONSTRAINT DF_Users_CreatedAt DEFAULT SYSUTCDATETIME(),
  UpdatedAt DATETIME2 NOT NULL CONSTRAINT DF_Users_UpdatedAt DEFAULT SYSUTCDATETIME()
);

CREATE UNIQUE INDEX UX_Users_Email ON dbo.Users (Email);
CREATE UNIQUE INDEX UX_Users_RegistrationNumber_NotNull
  ON dbo.Users (RegistrationNumber)
  WHERE RegistrationNumber IS NOT NULL;

-- News
CREATE TABLE dbo.News (
  Id UNIQUEIDENTIFIER NOT NULL CONSTRAINT PK_News PRIMARY KEY DEFAULT NEWID(),
  Title NVARCHAR(255) NOT NULL,
  Summary NVARCHAR(MAX) NULL,
  Content NVARCHAR(MAX) NOT NULL,
  ImageUrl NVARCHAR(2048) NULL,
  Author NVARCHAR(120) NULL,
  Published BIT NOT NULL CONSTRAINT DF_News_Published DEFAULT (0),
  CreatedAt DATETIME2 NOT NULL CONSTRAINT DF_News_CreatedAt DEFAULT SYSUTCDATETIME()
);

-- Partners
CREATE TABLE dbo.Partners (
  Id UNIQUEIDENTIFIER NOT NULL CONSTRAINT PK_Partners PRIMARY KEY DEFAULT NEWID(),
  Title NVARCHAR(255) NOT NULL,
  Description NVARCHAR(MAX) NULL,
  ImageUrl NVARCHAR(2048) NULL,
  FacebookUrl NVARCHAR(2048) NULL,
  CreatedAt DATETIME2 NOT NULL CONSTRAINT DF_Partners_CreatedAt DEFAULT SYSUTCDATETIME()
);

-- Team members
CREATE TABLE dbo.TeamMembers (
  Id UNIQUEIDENTIFIER NOT NULL CONSTRAINT PK_TeamMembers PRIMARY KEY DEFAULT NEWID(),
  Name NVARCHAR(120) NOT NULL,
  Title NVARCHAR(255) NULL,
  Description NVARCHAR(MAX) NULL,
  Bio NVARCHAR(MAX) NULL,
  ImageUrl NVARCHAR(2048) NULL,
  CreatedAt DATETIME2 NOT NULL CONSTRAINT DF_TeamMembers_CreatedAt DEFAULT SYSUTCDATETIME()
);

-- Mission & Vision (single-row table; allow multiple rows if you want history)
CREATE TABLE dbo.MissionVision (
  Id UNIQUEIDENTIFIER NOT NULL CONSTRAINT PK_MissionVision PRIMARY KEY DEFAULT NEWID(),
  Mission NVARCHAR(MAX) NULL,
  Vision NVARCHAR(MAX) NULL,
  CreatedAt DATETIME2 NOT NULL CONSTRAINT DF_MissionVision_CreatedAt DEFAULT SYSUTCDATETIME()
);

-- Our Story (single-row table; allow multiple rows if you want history)
CREATE TABLE dbo.OurStory (
  Id UNIQUEIDENTIFIER NOT NULL CONSTRAINT PK_OurStory PRIMARY KEY DEFAULT NEWID(),
  Story NVARCHAR(MAX) NULL,
  CreatedAt DATETIME2 NOT NULL CONSTRAINT DF_OurStory_CreatedAt DEFAULT SYSUTCDATETIME()
);

-- About Us cards (from your "aboutus" collection)
CREATE TABLE dbo.AboutUsCards (
  Id UNIQUEIDENTIFIER NOT NULL CONSTRAINT PK_AboutUsCards PRIMARY KEY DEFAULT NEWID(),
  Title NVARCHAR(255) NOT NULL,
  Description NVARCHAR(MAX) NULL,
  ImageUrl NVARCHAR(2048) NULL,
  FacebookUrl NVARCHAR(2048) NULL,
  CreatedAt DATETIME2 NOT NULL CONSTRAINT DF_AboutUsCards_CreatedAt DEFAULT SYSUTCDATETIME()
);

-- Chats
CREATE TABLE dbo.Chats (
  Id UNIQUEIDENTIFIER NOT NULL CONSTRAINT PK_Chats PRIMARY KEY DEFAULT NEWID(),
  IsGroup BIT NOT NULL CONSTRAINT DF_Chats_IsGroup DEFAULT (0),
  CreatedAt DATETIME2 NOT NULL CONSTRAINT DF_Chats_CreatedAt DEFAULT SYSUTCDATETIME()
);

CREATE TABLE dbo.ChatParticipants (
  ChatId UNIQUEIDENTIFIER NOT NULL,
  UserId UNIQUEIDENTIFIER NOT NULL,
  CreatedAt DATETIME2 NOT NULL CONSTRAINT DF_ChatParticipants_CreatedAt DEFAULT SYSUTCDATETIME(),
  CONSTRAINT PK_ChatParticipants PRIMARY KEY (ChatId, UserId),
  CONSTRAINT FK_ChatParticipants_Chat FOREIGN KEY (ChatId) REFERENCES dbo.Chats(Id),
  CONSTRAINT FK_ChatParticipants_User FOREIGN KEY (UserId) REFERENCES dbo.Users(Id)
);

CREATE TABLE dbo.ChatMessages (
  Id UNIQUEIDENTIFIER NOT NULL CONSTRAINT PK_ChatMessages PRIMARY KEY DEFAULT NEWID(),
  ChatId UNIQUEIDENTIFIER NOT NULL,
  SenderUserId UNIQUEIDENTIFIER NOT NULL,
  ReceiverUserId UNIQUEIDENTIFIER NULL,
  Type NVARCHAR(16) NOT NULL CONSTRAINT DF_ChatMessages_Type DEFAULT N'text',
  Text NVARCHAR(MAX) NULL,
  FileUrl NVARCHAR(2048) NULL,
  FileName NVARCHAR(255) NULL,
  CreatedAt DATETIME2 NOT NULL CONSTRAINT DF_ChatMessages_CreatedAt DEFAULT SYSUTCDATETIME(),
  ReadAt DATETIME2 NULL,
  CONSTRAINT FK_ChatMessages_Chat FOREIGN KEY (ChatId) REFERENCES dbo.Chats(Id),
  CONSTRAINT FK_ChatMessages_Sender FOREIGN KEY (SenderUserId) REFERENCES dbo.Users(Id),
  CONSTRAINT FK_ChatMessages_Receiver FOREIGN KEY (ReceiverUserId) REFERENCES dbo.Users(Id)
);

CREATE INDEX IX_ChatMessages_ChatId_CreatedAt ON dbo.ChatMessages (ChatId, CreatedAt);

-- Stories
CREATE TABLE dbo.Stories (
  Id UNIQUEIDENTIFIER NOT NULL CONSTRAINT PK_Stories PRIMARY KEY DEFAULT NEWID(),
  UserId UNIQUEIDENTIFIER NOT NULL,
  ImageUrl NVARCHAR(2048) NOT NULL,
  Caption NVARCHAR(255) NULL,
  CreatedAt DATETIME2 NOT NULL CONSTRAINT DF_Stories_CreatedAt DEFAULT SYSUTCDATETIME(),
  ExpiresAt DATETIME2 NOT NULL,
  CONSTRAINT FK_Stories_User FOREIGN KEY (UserId) REFERENCES dbo.Users(Id)
);

CREATE TABLE dbo.StoryViews (
  StoryId UNIQUEIDENTIFIER NOT NULL,
  ViewerUserId UNIQUEIDENTIFIER NOT NULL,
  ViewedAt DATETIME2 NOT NULL CONSTRAINT DF_StoryViews_ViewedAt DEFAULT SYSUTCDATETIME(),
  CONSTRAINT PK_StoryViews PRIMARY KEY (StoryId, ViewerUserId),
  CONSTRAINT FK_StoryViews_Story FOREIGN KEY (StoryId) REFERENCES dbo.Stories(Id),
  CONSTRAINT FK_StoryViews_User FOREIGN KEY (ViewerUserId) REFERENCES dbo.Users(Id)
);

